# URL de conexão: jdbc:postgresql://<host>:<porta>/<nome_do_banco>
spring.datasource.url=jdbc:postgresql://localhost:5432/db_lembrete

# Credenciais de acesso
spring.datasource.username=postgres
spring.datasource.password=root

# Driver do PostgreSQL (Opcional a partir do Spring Boot 2.x, pois é autodetectado)
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
# Porta padrão para criptografia TLS explícita (STARTTLS)
spring.mail.port=587
spring.mail.username=seu-email@gmail.com
# Cole aqui os 16 dígitos gerados pelo Google (ex: ijstptgawqasytui)
spring.mail.password=sua_senha_de_app_aqui

# Propriedades obrigatórias para o protocolo SMTP do Gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
